### PR TITLE
check for jumps during execution

### PR DESCRIPTION
**Pull request by OriolAbril**
I think we should make the check more strict or add a config argument to make the check more strict.

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Hey @OriolAbril 

Sure, that's a good suggestion - how about a `--strict` flag?

---

I may not have documented this, but to run the tests you can do `pip install tox`, then `tox -e py`, in some virtual environment with py36, py37, py38 or py39

**Comment by OriolAbril** [comment]
> Sure, that's a good suggestion - how about a --strict flag?

Sounds good

> I may not have documented this, but to run the tests you can do pip install tox, then tox -e py, in some virtual environment with py36, py37, py38 or py39

Good to know, I didn't modify anything related to tests yet because the bad notebook has cells with execution number 2 first, then execution number 1. With this stricter change it fails at the first cell instead of the second, and the error message is different. I wasn't sure what was the best way to modify it, especially depending on argument/no argument option.

**Comment by MarcoGorelli** [comment]
I'd suggest adding a `--strict` flag after this line:

https://github.com/MarcoGorelli/check-execution-order/blob/b56d9bdbda7307d39c0cdcee412aabe81fab3a95/check_execution_order.py#L38

and then making a new test case for when `strict=True`

**Comment by MarcoGorelli** [comment]
thanks for picking this up again! Looks like it's almost there, the test just needs fixing up

once it's in I'll add this to https://github.com/MarcoGorelli/madforhooks , not worth having its own repo for this

**Comment by OriolAbril** [comment]
How should I call `main` when using the strict flag? I have searched a bit and wasn't able to find it. I did test yesterday as a command line program and it did work with all 3 files

**Comment by MarcoGorelli** [comment]
Does
```python
    ret = main(
        (
            path, '--strict=True',
        ),
    )
```
work?

If not I'll try running this later

**Comment by OriolAbril** [comment]
fixed, the action for the flag is store_true so the `=True` is not needed, having the flag by itself is the indicator

**Review by MarcoGorelli — APPROVED** [review]
cool, thanks for doing this! will make a release soon

**Pull request merged**
